name: "Package xbridge_witnessd"
on:
  push:
    branches: ['main', 'release', 'develop', '*-rc[0-9]+', '*-b[0-9]+']
  workflow_dispatch:

jobs:
  package:
      name: Build
      runs-on: [self-hosted, x-heavy]
      container:
        image: gcc:11
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Build
          uses: ./.github/actions/build

        # - name: Run unit tests
        #   uses: ./.github/actions/build

        - name: Save server
          uses: actions/upload-artifact@v3
          with:
            name: xbwd
            path: build/xbridge_witnessd
